### ISSUE TITLE
Weird pathfinding in some situations

### ISSUE THREAD

**Issue by LyubomirT** [devYaksha/BIM-Pathfinding#2]
Found this glitch while playing around with the application after implementing #1. I don't have a clear idea of why the glitch occurs, but still would like to share in case anyone knows.

[foundabug.webm](https://github.com/devYaksha/BIM-Pathfinding/assets/127299159/eee8c071-7da2-467b-8f6d-04a847c3b10b)

**Comment by devYaksha** [comment]
Maybe this is a problem when the matrix is saved in bpm and the bpm is converted to tuples (x,y,cor). I'll try to find out. Thank you for your help!

**Comment by LyubomirT** [comment]
> Maybe this is a problem when the matrix is saved in bpm and the bpm is converted to tuples (x,y,cor). I'll try to find out. Thank you for your help!

You'we welcome! Hope this issue gets fixed soon.

**Comment by devYaksha** [comment]
Sorted out. I wasn't clearing the pre-existing dictionary of nodes at runtime, so when I added a new array, the new "walls" were route nodes in the dictionary.
